name: E2E Tests

on:
  workflow_call:
    inputs:
      sitemaps:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.generate_shards.outputs.shards }}
    steps:

      - name: Clone municipio-e2e-tests repository
        run: git clone https://github.com/helsingborg-stad/municipio-e2e-tests.git .

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.3'

      - name: Cache Composer dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install
      
      - name: Generate E2E shards
        id: generate_shards
        run: |
          SITEMAP_URLS="${{ inputs.sitemaps }}" composer generate:shards
          shards=$(composer generate-actions-matrix )
          echo "Generated shards: $shards"
          echo "shards=$shards" >> "$GITHUB_OUTPUT"
      
      - name: Upload shard files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: output
          path: output

  run:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.setup.outputs.shards) }}
    steps:

      - name: Clone municipio-e2e-tests repository
        run: git clone https://github.com/helsingborg-stad/municipio-e2e-tests.git .

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.3'

      - name: Cache Composer dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Download shard files
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: output
          path: output

      - name: List downloaded files
        run: ls -al output

      - name: List files in root
        run: ls -al

      - name: Run E2E tests
        run: SHARD_FILE="${{ matrix.shard }}" composer run run:smoketest